### PR TITLE
v11 release

### PR DESCRIPTION
**Pull request by CHBMB**

### CODE REVIEW

**Review by Roxedus — APPROVED** [review]

**Comment by CHBMB** [comment]
Spotted an issue here with the versioning.

`lspipepr/airsonic-advanced:amd64-v11-v10.6.0-pkg-none-pr-3`

**Comment by CHBMB** [comment]
Can get the appropriate release with:

`curl -sX GET "https://api.github.com/repos/airsonic-advanced/airsonic-advanced/releases" \
    | jq -r 'first(.[] | select(.prerelease == true)) | .tag_name'`

**Comment by CHBMB** [comment]
Thanks @aptalca.  That worked!

**Comment by TheSpad** [comment]
Superseded by https://github.com/linuxserver/docker-airsonic-advanced/pull/5

**Pull request closed without merging**
